apiVersion: v1
kind: Pod
metadata:
  name: secretpod
  labels:
    topic: secrets
spec:
  containers:
  - name: secret-ctr
    image: nginx
    env:
    - name: secUser
      valueFrom:
        secretKeyRef:
          name: creds   
          key: user    
    - name: secPass
      valueFrom:
        secretKeyRef:
          name: creds
          key: pwd
