apiVersion: v1
data:
  pwd: cHJvdmEK
  user: cGlwcG8K
kind: Secret
metadata:
  creationTimestamp: "2026-07-08T09:09:53Z"
  name: creds
  namespace: default
  resourceVersion: "414"
  uid: edbe05aa-48a1-46b6-9d45-0630fa01fb94
type: Opaque
