---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: formazione-sou
  name: jenkins-admin
rules:
  - verbs: ["*"]  #allow actions:
    apiGroups: [""] #on resources:
    resources: ["*"] #of type: (esempio: "pods", "deployments", "services", "replicasets", "configmaps", "secrets")
    
---
apiVersion: v1
kind: ServiceAccount #service account per jenkins, altrimenti users
metadata:
  name: jenkins-admin
  namespace: formazione-sou
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: formazione-sou

