
Vagrant.configure("2") do |config|
   config.vm.define "vm1" do |node1|
   	node1.vm.box = "ubuntu/jammy64"
  	node1.vm.hostname = "vm1"
   	node1.vm.network "forwarded_port", guest: 80, host: 8060
   	config.vm.provision "ansible" do |ansible|
   		ansible.playbook = "playbook.yml"
	end   
    end
end
