Vagrant.configure("2") do |config|
  # Usiamo /vagrant che esiste di default
  config.vm.define "vm1" do |node1|
    node1.vm.box = "ubuntu/jammy64"
    node1.vm.hostname = "vm1"
    node1.vm.provision "shell", path: "script.sh", args: "vm1"
    node1.vm.network "forwarded_port", guest: 3000, host: 3001
  end

  config.vm.define "vm2" do |node2|
    node2.vm.box = "ubuntu/jammy64"
    node2.vm.hostname = "vm2"
    node2.vm.provision "shell", path: "script.sh", args: "vm2"
    node2.vm.network "forwarded_port", guest: 3000, host: 3002
  end
end

