replicaCount: 1

image:
  repository: giulia00/formazione_sou_k8s
  pullPolicy: Always
  tag: ""
service:
  name: appflask
  type: ClusterIP
  port: 80
  internalPort: 5000

resources:
  limits:
    cpu: 200m        
    memory: 256Mi    
  requests:
    cpu: 100m        
    memory: 128Mi

nodeSelector: {}