---
- hosts: localhost
  become: true

  tasks:
 
    - name: Set limiti
      ansible.builtin.template:
        src: config.j2
        dest: output.txt
    
    - name: change limit.conf
      ansible.builtin.blockinfile:
          path: /etc/security/limits.conf
          
          block: |
            giuliagianfrancesco hard nofile {{ lookup('ansible.builtin.file',
                                 'output.txt') }}
          insertafter: EOF
          create: yes
