
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: formazione-sou
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding            
metadata:
  name: jenkins-admin-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
  - kind: ServiceAccount
    name: jenkins-admin
    namespace: formazione-sou