Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |node1|
    node1.vm.box = "bento/rockylinux-9"
    node1.vm.hostname = "vm1"
    node1.vm.network "forwarded_port", guest: 3000, host: 3010
    node1.vm.network "private_network", ip: "192.168.56.11"
#    config.vm.provision "ansible" do |ansible|
 #     ansible.playbook = "playbook.yml"
    
 # end

  end

  config.vm.define "vm2" do |node2|
    node2.vm.box = "bento/rockylinux-9"
    node2.vm.hostname = "vm2"
    node2.vm.network "forwarded_port", guest: 3000, host: 3011
    node2.vm.network "private_network", ip: "192.168.56.12"
  #  config.vm.provision "ansible" do |ansible|
   #   ansible.playbook = "playbook.yml"
    
 # end

end
end
